[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[ui]
hideSidebarNav = true

[theme]
base = "dark"
font = "sans serif"

[runner]
fastReruns = true

[client]
toolbarMode = "minimal"
showErrorDetails = true 